export type {contactType} from './contactType'
export type {navigationMenuType} from './navigationMenuType'
export type {buttonProps} from './buttonProps'
export type {projectProps} from './projectProps'
export type {imgProps} from './imgProps'